name: Run-Xtensa

# This is the entry point for xtensa.yml for scheduled and workflow_dispatch events. 


on:
  schedule:
    # 10am UTC is 3am or 4am PT depending on daylight savings.
    - cron: '0 10 * * *'

  # Allow manually triggering of the workflow.
  workflow_dispatch: {}

jobs:
  call-xtensa-dispatched:
    uses: ./.github/workflows/xtensa.yml
    if: |
      github.event_name == 'workflow_dispatch' 
    with:
      trigger-sha: ${{ github.sha }}
      is-dispatched: 'TRUE'
    secrets:
      tflm-bot-token: ${{ secrets.TFLM_BOT_PACKAGE_READ_TOKEN }}

  call-xtensa-scheduled:
    uses: ./.github/workflows/xtensa.yml
    if: |
      (github.event_name == 'schedule' && github.repository == 'tensorflow/tflite-micro')
    with:
      trigger-sha: ${{ github.sha }}
      is-scheduled: 'TRUE'
    secrets:
      tflm-bot-token: ${{ secrets.TFLM_BOT_PACKAGE_READ_TOKEN }}